In [3]:
import numpy
vector = numpy.array([5,10,15,20])
# 对所有元素判断是否等于10
vector == 10

array([False,  True, False, False])

In [4]:
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60]])
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [6]:
vector = numpy.array([5,10,15,20])
equal_to_ten = (vector == 10)
print(equal_to_ten)
# equal_to_ten 布尔值的数组可以当做索引来查找，对二维矩阵同样适用
print(vector[equal_to_ten])

[False  True False False]
[10]


In [8]:
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60]])

second_column_25 = (matrix[:,1] == 25)
print(second_column_25)
print(matrix[second_column_25,:])


[False  True False False]
[[20 25 30]]


In [10]:
vector = numpy.array([5,10,15,20])
equal_to_ten_or_five = (vector == 10) | (vector ==5)
print(equal_to_ten_or_five)
# equal_to_ten 布尔值的数组可以当做索引来查找，对二维矩阵同样适用
print(vector[equal_to_ten_or_five])


[ True  True False False]
[ 5 10]


In [12]:
#类型转换
vector = numpy.array(['1','2','3'])
print(vector)
print(vector.dtype)
vector = vector.astype(float)
print(vector)
print(vector.dtype)


['1' '2' '3']
<U1
[1. 2. 3.]
float64


In [14]:
vector.min()
# print(help(numpy.array))

1.0

In [18]:
#axis等于0,表示对列求和
matrix.sum(axis=0)


array([110, 130, 150])

In [19]:
#axis等1 表示按行求和
matrix.sum(axis=1)

array([ 30,  75, 120, 165])