In [1]:
import numpy

In [2]:
house_price = numpy.genfromtxt("ex1data1.txt",delimiter=',',dtype=str)

In [3]:
print(house_price)

[['2104' '3' '399900']
 ['1600' '3' '329900']
 ['2400' '3' '369000']
 ['1416' '2' '232000']
 ['3000' '4' '539900']
 ['1985' '4' '299900']
 ['1534' '3' '314900']
 ['1427' '3' '198999']
 ['1380' '3' '212000']
 ['1494' '3' '242500']
 ['1940' '4' '239999']
 ['2000' '3' '347000']
 ['1890' '3' '329999']
 ['4478' '5' '699900']
 ['1268' '3' '259900']
 ['2300' '4' '449900']
 ['1320' '2' '299900']
 ['1236' '3' '199900']
 ['2609' '4' '499998']
 ['3031' '4' '599000']
 ['1767' '3' '252900']
 ['1888' '2' '255000']
 ['1604' '3' '242900']
 ['1962' '4' '259900']
 ['3890' '3' '573900']
 ['1100' '3' '249900']
 ['1458' '3' '464500']
 ['2526' '3' '469000']
 ['2200' '3' '475000']
 ['2637' '3' '299900']
 ['1839' '2' '349900']
 ['1000' '1' '169900']
 ['2040' '4' '314900']
 ['3137' '3' '579900']
 ['1811' '4' '285900']
 ['1437' '3' '249900']
 ['1239' '3' '229900']
 ['2132' '4' '345000']
 ['4215' '4' '549000']
 ['2162' '4' '287000']
 ['1664' '2' '368500']
 ['2238' '3' '329900']
 ['2567' '4' '314000']
 ['1200' '3

In [4]:
#1维向量的构造
vector = numpy.array([5,10,15,20])
#2维向量的构造
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60]])
print(vector)
print(matrix)

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]]


In [5]:
# shape 函数打印出向量的行，列
vector = numpy.array([1,2,3,4])
print(vector.shape)
print(matrix.shape)

(4,)
(4, 3)


In [6]:
import numpy

#numpy.array 里面的元素必须是相同的结构
# numbers = numpy.array([1,2,3,4.0,5])
numbers = numpy.array([1,2,3,'4',5])
print(numbers)
numbers.dtype


['1' '2' '3' '4' '5']


dtype('<U21')

In [8]:
print(house_price[1,2])

329900


In [10]:
vector = numpy.array([1,2,3,4,5])


#取数组的第0-3元素 左闭右开
print(vector[0:3])

[1 2 3]


In [13]:
#冒号表示所有的，第一个参数表示所有的行，第二个参数表示第1列
print(matrix[:,1])
#冒号表示所有的，第一个参数表示所有的行，第二个参数表示第0-2列
print(matrix[:,0:2])

print(matrix[1:3,0:2])

[10 25 40 55]
[[ 5 10]
 [20 25]
 [35 40]
 [50 55]]
[[20 25]
 [35 40]]
