In [2]:
import numpy as np

In [7]:
print(np.arange(15))
a=np.arange(15).reshape(3,5)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
a.shape

(3, 5)

In [10]:
#获取数组的维度
a.ndim

2

In [11]:
a.dtype.name

'int64'

In [13]:
#3*4的空矩阵
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#值全是1的矩阵
np.ones((2,3,4),dtype=np.str)

array([[['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']],

       [['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']]], dtype='<U1')

In [17]:
#10-30，以5为间隔的数组
np.arange(10,30,5)


array([10, 15, 20, 25])

In [18]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [20]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
#随机生成2*3的矩阵
np.random.random((2,3))

array([[0.02588924, 0.25887623, 0.73784951],
       [0.78272771, 0.82136677, 0.19799388]])

In [23]:
from numpy import pi

# 指定区间，得到100个间隔相等的数
np.linspace(0,2*pi,100)


array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [27]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

c = a-b
print(c)
c = c-1
print(c)

# b的平方
print(b**2)
print(a<35)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[19 28 37 46]
[0 1 4 9]
[ True  True False False]


In [29]:

#  * 表示对于位置的乘法，点乘    
# .dot表示矩阵的乘法
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print(A*B)
print(A.dot(B))
print(np.dot(A,B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [30]:
B = np.arange(3)
print(B)
# e的B次方
print(np.exp(B))
# B元素每个值开根号
print(np.sqrt(B))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [37]:
#floor向下取整
a = np.floor(10*np.random.random((3,4)))

print(a)
print('------------')

#ravel 与shape相反，
print(a.ravel())
print('------------')
# 转换成6*2的矩阵
a.shape=(6,2)
print(a)
print('------------')

#a矩阵的转置
print(a.T)

#指定一个维度，另外一个维度也确认了，-1表示自动计算第二维的数量
#reshape(3,-1) 

[[7. 5. 3. 1.]
 [4. 0. 1. 6.]
 [3. 0. 8. 3.]]
------------
[7. 5. 3. 1. 4. 0. 1. 6. 3. 0. 8. 3.]
------------
[[7. 5.]
 [3. 1.]
 [4. 0.]
 [1. 6.]
 [3. 0.]
 [8. 3.]]
------------
[[7. 3. 4. 1. 3. 8.]
 [5. 1. 0. 6. 0. 3.]]


In [40]:
# np.hstack((a,b))表示水平方向拼接  vstack表示竖直方向拼接
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print(np.hstack((a,b)))
print(np.vstack((a,b)))


[[1. 0. 4. 8.]
 [1. 2. 9. 0.]]
[[1. 0.]
 [1. 2.]
 [4. 8.]
 [9. 0.]]


In [42]:
#数组的拆分
#hsplit(a,3) 将a 横向拆分成3份
# vsplit(a,2） 将a竖直拆分成2份
a = np.floor(10*np.random.random((2,12)))
print(a)
print(np.hsplit(a,3))

[[4. 8. 5. 3. 2. 7. 3. 7. 5. 8. 3. 1.]
 [8. 0. 0. 3. 5. 2. 3. 9. 2. 2. 1. 8.]]
[array([[4., 8., 5., 3.],
       [8., 0., 0., 3.]]), array([[2., 7., 3., 7.],
       [5., 2., 3., 9.]]), array([[5., 8., 3., 1.],
       [2., 2., 1., 8.]])]
